import {useEffect,useMemo,useState} from 'react'
import './App.css'
import './Method.css'
import {api} from './api/client'
import type {GraphData,Option,Recipe,RecipeDetail,SearchRequest} from './types'

const initial:SearchRequest={ingredientIds:[],applianceIds:[],cuisineId:'',dietIds:[],maxCookTimeMinutes:null}
const icon=(method:string)=>method.includes('AIR')?'✦':method.includes('SIMMER')?'◒':method.includes('NO')?'❋':'◉'
function toggle(list:string[],id:string){return list.includes(id)?list.filter(x=>x!==id):[...list,id]}

function App(){
 const [page,setPage]=useState<'discover'|'graph'>('discover'),[options,setOptions]=useState<{ingredients:Option[];cuisines:Option[];diets:Option[];appliances:Option[]}|null>(null)
 const [form,setForm]=useState(initial),[query,setQuery]=useState(''),[recipes,setRecipes]=useState<Recipe[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false),[detail,setDetail]=useState<RecipeDetail|null>(null)
 useEffect(()=>{api.options().then(setOptions).catch(e=>setError(e.message))},[])
 const filtered=useMemo(()=>options?.ingredients.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())&&!form.ingredientIds.includes(x.id)).slice(0,8)||[],[options,query,form.ingredientIds])
 async function search(){setLoading(true);setError('');setSearched(true);try{setRecipes(await api.search(form))}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{setLoading(false)}}
 async function openRecipe(id:string){setLoading(true);try{setDetail(await api.recipe(id,form.ingredientIds))}catch(e){setError(e instanceof Error?e.message:'Recipe unavailable')}finally{setLoading(false)}}
 return <><header><button className="brand" onClick={()=>setPage('discover')}><span>FG</span>FlavorGraph</button><nav><button className={page==='discover'?'active':''} onClick={()=>setPage('discover')}>Discover</button><button className={page==='graph'?'active':''} onClick={()=>setPage('graph')}>Explore graph <i>↗</i></button></nav></header>
 {page==='graph'?<GraphPage openRecipe={openRecipe}/>:<main>
  <section className="hero"><div><p className="eyebrow">Your pantry, connected</p><h1>Cook smarter with<br/><em>what you already have.</em></h1><p>Pick what’s in your kitchen. We’ll follow the connections and find recipes that fit.</p></div><div className="hero-art"><span className="orbit one">Garlic</span><span className="orbit two">Chicken</span><span className="orbit three">Potato</span><div className="plate">✣<small>good food<br/>starts here</small></div></div></section>
  <section className="finder"><div className="step"><b>01</b><div><h2>What’s in your kitchen?</h2><p>Select every ingredient you have on hand.</p></div></div>
   <div className="picker"><div className="chips">{form.ingredientIds.map(id=><button key={id} onClick={()=>setForm({...form,ingredientIds:toggle(form.ingredientIds,id)})}>{options?.ingredients.find(x=>x.id===id)?.name} ×</button>)}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ingredients…"/></div>{query&&<div className="suggestions">{filtered.map(x=><button key={x.id} onClick={()=>{setForm({...form,ingredientIds:[...form.ingredientIds,x.id]});setQuery('')}}><span>+</span>{x.name}<small>{x.category}</small></button>)}</div>}</div>
   <div className="step appliance-step"><b>02</b><div><h2>How can you cook?</h2><p>Choose the appliances you have.</p></div></div><div className="choice-row">{options?.appliances.map(x=><button className={form.applianceIds.includes(x.id)?'selected':''} onClick={()=>setForm({...form,applianceIds:toggle(form.applianceIds,x.id)})} key={x.id}><span>{x.id==='air-fryer'?'♨':x.id==='oven'?'▤':x.id==='stovetop'?'◉':x.id==='microwave'?'▥':'◒'}</span>{x.name}</button>)}</div>
   <div className="filters"><label>Cuisine<select value={form.cuisineId} onChange={e=>setForm({...form,cuisineId:e.target.value})}><option value="">Any cuisine</option>{options?.cuisines.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Diet<select value={form.dietIds[0]||''} onChange={e=>setForm({...form,dietIds:e.target.value?[e.target.value]:[]})}><option value="">Any diet</option>{options?.diets.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Max time<select value={form.maxCookTimeMinutes||''} onChange={e=>setForm({...form,maxCookTimeMinutes:e.target.value?Number(e.target.value):null})}><option value="">Any time</option><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="45">45 minutes</option></select></label></div>
   <button className="find" disabled={loading} onClick={search}>{loading?'Finding recipes…':'Find recipes'} <span>→</span></button>
  </section>
  {error&&<div className="state error"><b>We couldn’t reach the kitchen.</b><p>{error}</p><button onClick={()=>{setError('');search()}}>Try again</button></div>}
  {searched&&!loading&&!error&&<section className="results"><div className="results-head"><div><p className="eyebrow">Made for your pantry</p><h2>{recipes.length} recipes worth making</h2></div><span>Ranked by ingredient match</span></div>{recipes.length===0?<div className="state"><b>No recipes matched those filters.</b><p>Try removing a filter or adding another ingredient.</p></div>:<div className="cards">{recipes.map((r,i)=><article key={r.id} onClick={()=>openRecipe(r.id)}><div className={`food food-${i%4}`}><span>{icon(r.cookingMethod)}</span><b>{r.ingredientMatchPercentage}% match</b></div><div className="card-body"><div className="meta"><span>{r.cuisine}</span><span>{r.cookTimeMinutes} min</span><span>{r.difficulty.toLowerCase()}</span></div><h3>{r.name}</h3><p>{r.description}</p><div className="badges">{r.diets.slice(0,2).map(d=><span key={d}>{d}</span>)}</div><footer><span className={r.missingIngredientCount?'missing':'complete'}>{r.missingIngredientCount?`${r.missingIngredientCount} missing`:'You have it all'}</span>{r.possibleWithSubstitutions&&<span className="sub">Substitute found</span>}<b>View recipe →</b></footer></div></article>)}</div>}</section>}
 </main>}
 {detail&&<RecipeModal recipe={detail} close={()=>setDetail(null)}/>}<footer className="site-footer"><b>FlavorGraph</b><span>Connections make dinner possible.</span><small>Ingredient substitutions are suggestions, not medical or allergen advice.</small></footer></>
}

function RecipeModal({recipe,close}:{recipe:RecipeDetail;close:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal"><button className="close" onClick={close}>×</button><p className="eyebrow">{recipe.cuisine} · {recipe.cookingMethod.replaceAll('_',' ')}</p><h2>{recipe.name}</h2><p className="lead">{recipe.description}</p><div className="recipe-meta"><span>◷ <b>{recipe.cookTimeMinutes} min</b></span><span>◇ <b>{recipe.difficulty.toLowerCase()}</b></span><span>♨ <b>{recipe.appliances.join(', ')}</b></span></div><h3>What you’ll need</h3><div className="ingredients">{recipe.ingredients.map(i=><div className={i.available?'owned':'needed'} key={i.id}><span className="check">{i.available?'✓':'!'}</span><div><b>{i.name}</b><small>{i.quantity} {i.unit} · {i.available?'In your pantry':'Missing'}</small>{!i.available&&i.substitutions.length>0&&<p>Don’t have {i.name}? Try <strong>{i.substitutions[0].name}</strong>. {i.substitutions[0].note}</p>}</div></div>)}</div><div className="diet-line">{recipe.diets.map(d=><span key={d}>{d}</span>)}</div><div className="method"><p className="eyebrow">Step by step</p><h3>Let’s make it</h3><ol>{(recipe.instructions??[]).map((step,index)=><li key={index}><span>{index+1}</span><p>{step}</p></li>)}</ol></div></section></div>}

function GraphPage({openRecipe}:{openRecipe:(id:string)=>Promise<void>}){const [data,setData]=useState<GraphData|null>(null),[selected,setSelected]=useState<GraphData['nodes'][number]|null>(null),[error,setError]=useState('');useEffect(()=>{api.graph().then(setData).catch(e=>setError(e.message))},[]);if(error)return <main className="graph-shell"><div className="state error"><b>Graph unavailable</b><p>{error}</p></div></main>;if(!data)return <main className="graph-shell"><div className="state"><b>Mapping the flavor graph…</b></div></main>;if(!data.nodes.length)return <main className="graph-shell"><div className="state"><b>No graph data available.</b></div></main>;
 const shown=data.nodes.slice(0,48), ids=new Set(shown.map(n=>n.id)),edges=data.edges.filter(e=>ids.has(e.source)&&ids.has(e.target));const positions=new Map(shown.map((n,i)=>[n.id,{x:70+(i%8)*135+(Math.floor(i/8)%2)*35,y:65+Math.floor(i/8)*105}]));return <main className="graph-shell"><div className="graph-title"><div><p className="eyebrow">Explore the connections</p><h1>Your food is a network.</h1><p>Recipes, ingredients, cuisines, diets and substitutions—all connected.</p></div><div className="legend">{['Recipe','Ingredient','Cuisine','Diet','Appliance'].map(x=><span className={x.toLowerCase()} key={x}><i/> {x}</span>)}</div></div><div className="graph-layout"><div className="canvas"><svg viewBox="0 0 1100 700" role="img" aria-label="FlavorGraph relationship explorer">{edges.map((e,i)=>{const a=positions.get(e.source),b=positions.get(e.target);return a&&b?<g key={i}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y}/></g>:null})}{shown.map(n=>{const p=positions.get(n.id)!;return <g className={`node ${n.label.toLowerCase()} ${selected?.id===n.id?'chosen':''}`} key={n.id} onClick={()=>setSelected(n)}><circle cx={p.x} cy={p.y} r={n.label==='Recipe'?30:23}/><text x={p.x} y={p.y+42}>{n.name.length>18?n.name.slice(0,17)+'…':n.name}</text><text className="glyph" x={p.x} y={p.y+5}>{n.label==='Recipe'?'✦':n.label==='Ingredient'?'●':'◇'}</text></g>})}</svg></div><aside><p className="eyebrow">Selected node</p>{selected?<><span className={`type ${selected.label.toLowerCase()}`}>{selected.label}</span><h2>{selected.name}</h2><p>{String(selected.properties.description||selected.properties.category||'A connected part of the FlavorGraph.')}</p>{selected.label==='Recipe'&&<button className="graph-recipe-button" onClick={()=>openRecipe(selected.id)}>View full recipe <span>→</span></button>}<h3>Connections</h3>{data.edges.filter(e=>e.source===selected.id||e.target===selected.id).slice(0,8).map((e,i)=>{const other=data.nodes.find(n=>n.id===(e.source===selected.id?e.target:e.source));return <div className="connection" key={i}><small>{e.type.replaceAll('_',' ')}</small><b>{other?.name}</b></div>})}</>:<div className="select-hint">Click a node to see how it connects.</div>}</aside></div></main>}
export default App
